apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: techcommerce
data:
  NODE_ENV: "production"
  PORT: "3000"
  PRODUCT_API_URL: "http://product-api-service:5003"
  ORDER_API_URL: "http://order-api-service:5004"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  LOG_LEVEL: "info"
  APP_NAME: "TechCommerce"
  APP_VERSION: "1.0.0"
