apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: techcommerce
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 5002 # External port (what other services call)
      targetPort: 5004 # Container port (where Flask runs)
  type: ClusterIP
