apiVersion: v1
kind: Service
metadata:
  name: product-api-service
  namespace: techcommerce
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 5001 # External port (what other services call)
      targetPort: 5003 # Container port (where Flask runs)
  type: ClusterIP
